[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "github.com/src-d/go-git"
  version = "4.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
